* iOS permissions
** Simulator
*** List simulators

    #+BEGIN_SRC shell
    xcrun simctl list
    #+END_SRC

*** Database

    ~/Library/Developer/CoreSimulator/Devices/<device>/data/Library/TCC/TCC.db

    <device> comes from previous list

    the `TCC.db` can use `sqlite3` to manipulate

    #+BEGIN_SRC sqlite
    insert into access values('kTCCServiceAddressBook','BundlerIdentifier', 0, 1, 0, 0, 0)
    #+END_SRC

    Predefined permissions:
    - calendar   => "kTCCServiceCalendar"
    - camera     => "kTCCServiceCamera"
    - contacts   => "kTCCServiceAddressBook"
    - microphone => "kTCCServiceMicrophone"
    - motion     => "kTCCServiceMotion"
    - photos     => "kTCCServicePhotos"
    - reminders  => "kTCCServiceReminders"
    - twitter    => "kTCCServiceTwitter"

    References:
    - [[https://github.com/google/EarlGrey/issues/55][EarlGrey]]
    - [[https://github.com/calabash/run_loop/pull/391][calabash]]
    - [[https://stackoverflow.com/questions/47159066/can-we-test-face-id-in-simulator][test faceid in ios simulator]]
    - [[https://github.com/wix/AppleSimulatorUtils][apple simulation utils]]
    - [[https://stackoverflow.com/questions/28443578/ios-permission-alerts-removing-or-suppressing][TCC]]
    - [[https://www.victorsigler.com/2018/01/29/simulator-permissions.html][iOS simulator permissions]]
    - [[https://github.com/wix/detox/issues/9][detox permission]]

**** Commands

***** .tables

***** .dump access

* e2e Framework

** Detox

   Cannot interact with system alert dialog such as permission. Since
   registry use custom keychain permission, if framework not provide
   this feature, than it has to modify code or try another one.

** Appium
* Apple Developer

** Bundle ID / Bundle Identifier

   A bundle ID or bundle identifier uniquely identifies an application
   in Apple's ecosystem, no two applications can have the same bundle
   identifier.

   Apple encourage using [[https://en.wikipedia.org/wiki/Reverse_domain_name_notation][reverse domain name notation]].

   for example:
   - com.cocoacasts.scribbles.ios
   - com.cocoacasts.scribbles.macos

** Apple ID

   An App ID represents one or more applications in Apple's system. It
   consists of two components, a Team ID and a bundle ID search
   string.

   for example: ABCDE12345.com.cocoacasts.scribbles

   ABCDE12345: team ID
   com.cocoacasts.scribbles bundle ID search string

* Mac argon2

** Location

   Linux pkg directory path is at [[https://askubuntu.com/questions/210210/pkg-config-path-environment-variable][here]]

   `/usr/local/Cellar/argon2/20171227/lib/pkgconfig/libargon2.pc`

** Add missing pkgconfig file

   #+BEGIN_SRC shell
     # libargon2 info for pkg-config
     ## Template for downstream installers:
     ## - replace @HOST_MULTIARCH@ with target arch, eg 'x86_64-linux-gnu'
     ## - replace @UPSTREAM_VER@ with current version, eg '20160406'

     prefix=/usr/local/Cellar/argon2/20171227
     exec_prefix=${prefix}
     libdir=${prefix}/lib
     includedir=${prefix}/include

     Name: libargon2
     Description: Development libraries for libargon2
     Version: 20171227
     Libs: -L${libdir} -largon2 -ldl
     Cflags:
     URL: https://github.com/P-H-C/phc-winner-argon2
   #+END_SRC

** Link

   at directory `/usr/local/lib/pkgconfig`

   ln -s ../../Cellar/argon2/20171227/lib/pkgconfig/libargon2.pc
